spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE