server:
  port: 4444

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_transaction
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


SECURE-USERNAME: admin
SECURE-PASSWORD: user1Pass
