
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DATABASE_URL}


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


